import { Question } from '@/types/survey';

export const SECTIONS = [
  { id: 1, name: 'About You' },
  { id: 2, name: 'The Struggle is Real' },
  { id: 3, name: 'The MetroMate Vision' },
  { id: 4, name: 'Trust & Access' },
];

export const QUESTIONS: Question[] = [
  // Section 1
  {
    id: 'q1_city',
    section: 1,
    sectionName: 'About You',
    questionNumber: 1,
    text: 'Which city are you headed to?',
    hint: 'Type the name of the city you\'re looking for a flat in.',
    type: 'text',
    required: true,
    placeholder: 'e.g. Pune, Mumbai, Bengaluru...',
  },
  {
    id: 'q2_role',
    section: 1,
    sectionName: 'About You',
    questionNumber: 2,
    text: 'What best describes you?',
    hint: 'Pick the option that fits you best.',
    type: 'single-select',
    options: ['Working professional', 'Student', 'Freelancer', 'Recently relocated', 'Other'],
    required: true,
  },
  {
    id: 'q3_housing',
    section: 1,
    sectionName: 'About You',
    questionNumber: 3,
    text: 'Your current housing situation?',
    hint: 'Where are you living right now?',
    type: 'single-select',
    options: ['Looking for a flat', 'Already in shared flat', 'Living alone', 'PG or hostel', 'With family'],
    required: true,
  },

  // Section 2
  {
    id: 'q4_pain',
    section: 2,
    sectionName: 'The Struggle is Real',
    questionNumber: 4,
    text: 'How painful has finding accommodation been?',
    hint: 'Be honest — we can take it.',
    type: 'scale',
    scaleMin: 1,
    scaleMax: 5,
    scaleMinLabel: 'Not painful',
    scaleMaxLabel: 'Extremely painful',
    required: false,
  },
  {
    id: 'q5_platforms',
    section: 2,
    sectionName: 'The Struggle is Real',
    questionNumber: 5,
    text: 'Which platforms have you tried?',
    hint: 'Select all that apply.',
    type: 'multi-select',
    options: [
      '99acres / MagicBricks',
      'Housing.com',
      'NoBroker',
      'Facebook groups',
      'WhatsApp circles',
      'Local broker',
      'Word of mouth',
      'OYO Life / Stanza',
    ],
    required: false,
  },
  {
    id: 'q6_frustration',
    section: 2,
    sectionName: 'The Struggle is Real',
    questionNumber: 6,
    text: 'What frustrated you most?',
    hint: 'Tell us in your own words — no filter needed.',
    type: 'textarea',
    required: false,
    placeholder: 'Brokers calling at 9pm, fake listings, ghost flatmates...',
  },

  // Section 3
  {
    id: 'q7_excitement',
    section: 3,
    sectionName: 'The MetroMate Vision',
    questionNumber: 7,
    text: 'How excited are you about a broker-free flatmate matching app?',
    hint: 'Imagine no broker fees, verified profiles, smart filters.',
    type: 'scale',
    scaleMin: 1,
    scaleMax: 5,
    scaleMinLabel: 'Meh',
    scaleMaxLabel: 'Take my money',
    required: true,
  },
  {
    id: 'q8_features',
    section: 3,
    sectionName: 'The MetroMate Vision',
    questionNumber: 8,
    text: 'Which features matter most to you?',
    hint: 'Pick up to 3 features you\'d use day one.',
    type: 'multi-select',
    options: [
      'Lifestyle filters',
      'Aadhaar verified',
      'Commute filter',
      'Gender preference',
      'Budget range',
      'In-app chat',
      'Flatmate reviews',
      'Rent agreement',
      'Expense splitting',
    ],
    maxSelections: 3,
    required: false,
  },
  {
    id: 'q9_pricing',
    section: 3,
    sectionName: 'The MetroMate Vision',
    questionNumber: 9,
    text: 'What would you pay to unlock a flatmate contact?',
    hint: 'Per connection, not a subscription.',
    type: 'single-select',
    options: [
      'Nothing – free only',
      '₹49–₹99',
      '₹100–₹199',
      '₹200–₹299/month',
      'More if worth it',
    ],
    required: false,
  },

  // Section 4
  {
    id: 'q10_trust',
    section: 4,
    sectionName: 'Trust & Access',
    questionNumber: 10,
    text: 'What would make you trust a stranger flatmate?',
    hint: 'Select all that would genuinely reassure you.',
    type: 'multi-select',
    options: [
      'Aadhaar verified',
      'Employer verified',
      'Past flatmate reviews',
      'Video profile',
      'Mutual connections',
      'Background check',
    ],
    required: false,
  },
  {
    id: 'q11_waitlist',
    section: 4,
    sectionName: 'Trust & Access',
    questionNumber: 11,
    text: 'Would you join the MetroMate early access waitlist?',
    hint: 'No spam. Just a heads-up when we launch in your city.',
    type: 'single-select',
    options: ['Yes, sign me up!', 'Maybe – tell me more', 'Not for me'],
    required: true,
  },
  {
    id: 'q12_email',
    section: 4,
    sectionName: 'Trust & Access',
    questionNumber: 12,
    text: 'Email address',
    hint: 'Optional — only if you want early access updates.',
    type: 'email',
    required: false,
    placeholder: 'you@email.com',
  },
  {
    id: 'q13_feedback',
    section: 4,
    sectionName: 'Trust & Access',
    questionNumber: 13,
    text: 'Anything else for us?',
    hint: 'Feature ideas, frustrations, love notes — we read everything.',
    type: 'textarea',
    required: false,
    placeholder: 'Build the thing already!',
  },
];

export const QUESTIONS_BY_SECTION = (section: number) =>
  QUESTIONS.filter((q) => q.section === section);

export const TOTAL_QUESTIONS = QUESTIONS.length;
